### ISSUE TITLE
Super Resolution Demo

### ISSUE THREAD

**Issue by nelaturuharsha** [aimerykong/predictive-filter-flow#13]
Hello,
Thank you so much for the contribution.
I read in a closed issue you planned to release a Super Resolution Demo, would you be releasing the same?

If possible, could you please nudge me in the right direction w.r.t to implementing it?

Thank you!

**Comment by aimerykong** [comment]
Hello,

Thanks for your interest!
Unfortunately I don't have the mood to release super-resolution demo for
now, as I'm busy with our paper re-submission.
Only after we get our paper accepted, I'll come back to release:-)

Based upon the released deblurring demo, I think the tweak for
super-resolution is to write your dataset function. For example, instead of
blurring the patches, you can consider down-sample and up-sampling the
image, then crop the corresponding patches to train the model (treat the
pairs as input and ground-truth).

Hope this helps!

Regards,
Shu
